# .goreleaser.yaml
version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - "386"
      - arm
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: "386"
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
    main: ./main.go
    binary: gridlock

archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE
      - README.md
      - .gridlock.example.yaml
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

aurs:
  - name: gridlock-bin
    homepage: "https://github.com/esaiaswestberg/gridlock"
    description: "A powerful TMUX session manager and automator"
    maintainers:
      - "Esaias Westberg <esaias@westbergs.se>"
    license: "MIT"
    private_key: '{{ .Env.AUR_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/gridlock-bin.git'
    depends:
      - tmux
    provides:
      - gridlock
    conflicts:
      - gridlock
    package: |-
      # bin
      install -Dm755 "./gridlock" "${pkgdir}/usr/bin/gridlock"
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/gridlock-bin/LICENSE"
      install -Dm644 "./README.md" "${pkgdir}/usr/share/doc/gridlock-bin/README.md"
      install -Dm644 "./.gridlock.example.yaml" "${pkgdir}/usr/share/doc/gridlock-bin/examples/.gridlock.example.yaml"

